name: Run Assignement 01.02

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-octave:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Octave
      run: sudo apt-get update && sudo apt-get install -y octave

    - name: Run Octave script
      run: octave --silent ./assignements/Assignement_01/Problem02/testing_actions.m
