name: Run Octave Tests on Github-Hosted Runner
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run tests
        uses: repos4u/octave-action@v1
        with:
          command: disp('Use any octave command ');
